### PR TITLE
Add "cathash" functionality

### PR DESCRIPTION
**Pull request by mmore500**
The main goal of this pull request is to add additional functionality to generate a single hash value for multiple files to the FileHash package. This is accomplished by sorting files their individual hash values and then traversing them in that order to generate a combined hash value.

In addition to new methods `cathash_files` and `cathash_dir`, I added accompanying unit tests, documentation in `README.rst`, and extensions to the CLI. 

Other changes along the way:
* allow CLI to take more than one filename as an argument
* add CLI parsing unit tests
* add `hash_files` method, which takes an iterable (e.g., a list) as an argument and returns a list of `FileHashResult`'s (analogously to the `cathash_dir` method)
* add `AUTHORS.rst`

If we merge this functionality, we'll probably want to bump the version and re-deploy to PyPi.

It was really fun working in this repository... well organized and well crafted! :100:

### CODE REVIEW

**Comment by NazarioJL** [comment]
👍

**Comment by NazarioJL** [comment]
I would like to add `xxhash` functionality as well. Is @leonidessaguisagjr interested in merging these in?

**Comment by leonidessaguisagjr** [comment]
@mmore500 My apologies for taking so long to merge this.  Thank you for all your hard work!

**Comment by leonidessaguisagjr** [comment]
@NazarioJL please feel free to create a pull request.  Thank you!

**Pull request merged**
